export * from './About';
export * from './Contact';
export * from './Login';
export * from './MainPage';
export * from './OAuth2RedirectHandler';
export * from './Profile';
export * from './Register';
export * from './MailActivation';
export * from './ForgotPassword';
export * from './ContentViewingPage';
export * from './ContentsView';
export * from './CategoryContentPage';
export * from './ContentMorePage';
export  * from './Comment'
export * from './SearchPage'
